(function() {var implementors = {};
implementors['bittorrent'] = ["<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='bittorrent/error/enum.TorrErrorKind.html' title='bittorrent::error::TorrErrorKind'>TorrErrorKind</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='bittorrent/peer/state/struct.PeerState.html' title='bittorrent::peer::state::PeerState'>PeerState</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='bittorrent/peer/state/enum.StateChange.html' title='bittorrent::peer::state::StateChange'>StateChange</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='bittorrent/torrent/enum.TorrFileType.html' title='bittorrent::torrent::TorrFileType'>TorrFileType</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='struct' href='bittorrent/tracker/struct.ScrapeInfo.html' title='bittorrent::tracker::ScrapeInfo'>ScrapeInfo</a>","<a class='stability Experimental' title='Experimental'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/kinds/trait.Copy.html' title='core::kinds::Copy'>Copy</a> for <a class='enum' href='bittorrent/util/enum.Transport.html' title='bittorrent::util::Transport'>Transport</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
