(function() {var implementors = {};
implementors['bittorrent'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='bittorrent/error/enum.TorrErrorKind.html' title='bittorrent::error::TorrErrorKind'>TorrErrorKind</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='bittorrent/peer/message/enum.StateChange.html' title='bittorrent::peer::message::StateChange'>StateChange</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='bittorrent/peer/struct.PeerState.html' title='bittorrent::peer::PeerState'>PeerState</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='bittorrent/torrent/enum.TorrFileType.html' title='bittorrent::torrent::TorrFileType'>TorrFileType</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='bittorrent/tracker/struct.ScrapeInfo.html' title='bittorrent::tracker::ScrapeInfo'>ScrapeInfo</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='bittorrent/types/struct.PeerID.html' title='bittorrent::types::PeerID'>PeerID</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='bittorrent/types/struct.InfoHash.html' title='bittorrent::types::InfoHash'>InfoHash</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='bittorrent/util/enum.Transport.html' title='bittorrent::util::Transport'>Transport</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
