(function() {var implementors = {};
implementors['byteorder'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; for <a class='enum' href='byteorder/enum.Error.html' title='byteorder::Error'>Error</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='byteorder/enum.Error.html' title='byteorder::Error'>Error</a>&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>",];implementors['redox'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='http://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt; for <a class='struct' href='redox/error/struct.TorrentError.html' title='redox::error::TorrentError'>TorrentError</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='struct' href='redox/error/struct.BencodeError.html' title='redox::error::BencodeError'>BencodeError</a>&gt; for <a class='struct' href='redox/error/struct.TorrentError.html' title='redox::error::TorrentError'>TorrentError</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.array.html'>[<a href='http://doc.rust-lang.org/nightly/std/primitive.u8.html'>u8</a>; INFO_HASH_LEN]</a>&gt; for <a class='struct' href='redox/struct.InfoHash.html' title='redox::InfoHash'>InfoHash</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
